sudo: false
language: python
branches:
  only:
    - master
before_install:
  - openssl aes-256-cbc -K $encrypted_5ca802f9d3d2_key -iv $encrypted_5ca802f9d3d2_iv -in publish-key.enc -out ~/.ssh/publish-key -d
  - chmod u=rw,og= ~/.ssh/publish-key
  - echo "Host github.com" >> ~/.ssh/config
  - echo "  IdentityFile ~/.ssh/publish-key" >> ~/.ssh/config
  - git remote set-url origin git@github.com:ITinDublin/itindublin.github.io.git
  - git fetch origin -f gh-pages:gh-pages
install:
  - pip install -r requirements.txt
script:
  - make html
deploy:
  provider: script
  script: make travis
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST = false
